### PR TITLE
Add proxy settings

### PR DESCRIPTION
**Pull request by macintoshplus**
This PR add the proxy configuration key for Guzzle.

Issue https://github.com/M6Web/GuzzleHttpBundle/issues/18

The "proxy" parameter key is optional.

### CODE REVIEW

**Comment by mojoLyon** [comment]
:+1: 

Could you please rebase this Pr ? it will be merged right after :)

**Comment by b-viguier** [comment]
:+1:

**Comment by omansour** [comment]
:+1: please just squash the 2 last commits

txs :)

**Comment by macintoshplus** [comment]
I rarely use git. My rebase does not operate. Sorry.

**Comment by omansour** [comment]
@mojoLyon maybe you can rebase the master after the merge. 

then tag the release

**Comment by macintoshplus** [comment]
Thanks you

**Comment by mojoLyon** [comment]
Thank to you for contributing

**Pull request merged**
