### PR TITLE
Patch/sf3 support

### PR DESCRIPTION
**Pull request by UgoSansH**

### CODE REVIEW

**Comment by jdlabails** [comment]
:+1:

**Comment by t-geindre** [comment]
:+1:

**Comment by mikaelrandy** [comment]
Originally, i asked myself why do you want to add a double pipe as one worked fine.
But [this documentation](https://getcomposer.org/doc/articles/versions.md#range) seems to say that the correct version is with double pipe.

So :+1:

**Comment by mikaelrandy** [comment]
v1.4.6

**Pull request merged**
